version: '3.8'

services:
  python:
    build: python
    environment:
      TZ: Asia/Tokyo
      HOST: 0.0.0.0
      PORT: 8000
    restart: always
    ports:
      - 8000:8000
  next:
    build: next
    environment:
      TZ: Asia/Tokyo
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - 3000:3000
    restart: always
  nginx:
    build: nginx
    ports:
      - 8086:80
    environment:
      TZ: Asia/Tokyo
    restart: always