name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
     branches:
      - master
      - dev

jobs:
  check-next:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: next
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: ${{env.WORKING_DIR}}

      - name: Lint ESLint
        run: yarn lint:eslint
        working-directory: ${{env.WORKING_DIR}}
        
      - name: Lint Prettier
        run: yarn lint:prettier
        working-directory: ${{env.WORKING_DIR}}
  
  check-python:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: python
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9.2
          
      - name: Install pipenv and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade-strategy=only-if-needed
          pipenv install --dev
          
      - name: Lint with flake8
        run: pipenv run lint
        
      - name: Test with pytest
        run: pipenv run test


