name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
     branches:
      - master
      - dev

jobs:
  lint-next:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: next
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: ${{env.WORKING_DIR}}

      - name: Lint ESLint
        run: yarn lint:eslint
        working-directory: ${{env.WORKING_DIR}}
        
      - name: Lint Prettier
        run: yarn lint:prettier
        working-directory: ${{env.WORKING_DIR}}

