name: Deploy to Docker Hub

on:
  push:
    paths-ignore:
      - .gitignore
      - LICENSE
      - '**.md'
    branches-ignore:
      - 'releases/**'

  release:
    types:
      - published

  workflow_dispatch:

env:
  PYTHON_DOCKER_IMAGE: iamtakagi/animelist-generator_python
  NEXT_DOCKER_IMAGE: iamtakagi/animelist-generator_next
  NGINX_DOCKER_IMAGE: iamtakagi/animelist-generator_nginx

  PYTHON_DOCKER_FILE: ./python/Dockerfile
  NEXTN_DOCKER_FILE: ./next/Dockerfile
  NGINXN_DOCKER_FILE: ./nginx/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Python
      - name: Build & Push (master) - Python
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.PYTHON_DOCKER_IMAGE }}:latest
          file: ${{ env.PYTHON_DOCKER_FILE }}
      - name: Build & Push (dev) - Python
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.PYTHON_DOCKER_IMAGE }}:dev
          file: ${{ env.PYTHON_DOCKER_FILE }}
      - name: Build & Push (Release) - Python
        if: github.event_name == 'release'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.PYTHON_DOCKER_IMAGE }}:${{ github.event.release.tag_name }}
          file: ${{ env.PYTHON_DOCKER_FILE }}
      
      # Next
      - name: Build & Push (master) - Next
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.NEXT_DOCKER_IMAGE }}:latest
          file: ${{ env.NEXT_DOCKER_FILE }}
      - name: Build & Push (dev) - Next
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.NEXT_DOCKER_IMAGE }}:dev
          file: ${{ env.NEXT_DOCKER_FILE }}
      - name: Build & Push (Release) - Next
        if: github.event_name == 'release'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.NEXT_DOCKER_IMAGE }}:${{ github.event.release.tag_name }}
          file: ${{ env.NEXT_DOCKER_FILE }}

      # Nginx
      - name: Build & Push (master) - Nginx
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.NGINX_DOCKER_IMAGE }}:latest
          file: ${{ env.NGINX_DOCKER_FILE }}
      - name: Build & Push (dev) - Nginx
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.NGINX_DOCKER_IMAGE }}:dev
          file: ${{ env.NGINX_DOCKER_FILE }}
      - name: Build & Push (Release) - Nginx
        if: github.event_name == 'release'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.NGINX_DOCKER_IMAGE }}:${{ github.event.release.tag_name }}
          file: ${{ env.NGINX_DOCKER_FILE }}